:Author: jnathan21
:Email: jnathanayala21@gmail.com
:Date: 12/02/2024
:Revision: version#
:License: Public Domain


Describe your project


El presente esta basado en un Proyecto que encontre en youtube, la implementacion que yo hice fue el ingreso  
de las variables Kp,Ki,Kd  y que estas se puedan modificar, cambiar y visualizar desde la dashboard 
de Arduino Iot Cloud, si encuentras un error o se puede mejorar el codigo
no dudes en hacermelo saber te dejo el link del video y mi correo tambien te dejo resumidos los pasos que debes hacer para crear la dashboard. 
Espero que este proyecto te sirva. 
Saludos. 




=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── Iot Cloud Pasos        => main Arduino file
  ├── PiD IOT CLOUD     => (optional) an image of the required schematics
  ├── PiD IOT Cloud.ino          => (optional) an image of the layout
  └── ReadMe         => this file
....

=== License
This project is released by Jonathan Ayala 

=== Contributing
This code is based on this video. https://www.youtube.com/watch?v=bl2k6eXDAGM

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name           | Part number | Quantity
| 1 | Esp32 NodeMcu        | 0000000000  | 1       
| 1 | Potenciometro 5k     | 0000000000  | 1       
| 1 | Puente H             | 0000000000  | 1  
| 1 | Motor con Encoder    | 0000000000  | 1 



=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
