// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "56735c0b-b755-401f-bdb5-a2ec2d2206b5";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onKdChange();
void onKiChange();
void onKpChange();
void onSpChange();
void onVelocidadChange();

float kd;
float ki;
float kp;
float sp;
float velocidad;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(kd, READWRITE, ON_CHANGE, onKdChange);
  ArduinoCloud.addProperty(ki, READWRITE, ON_CHANGE, onKiChange);
  ArduinoCloud.addProperty(kp, READWRITE, ON_CHANGE, onKpChange);
  ArduinoCloud.addProperty(sp, READWRITE, ON_CHANGE, onSpChange);
  ArduinoCloud.addProperty(velocidad, READWRITE, ON_CHANGE, onVelocidadChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
